//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bequeath
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bequeath()
        {
            this.ClientWills = new HashSet<ClientWill>();
        }
    
        public int BequeathID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IDNumberDOB { get; set; }
        public string ItemAmount { get; set; }
        public Nullable<int> BequeathTypeID { get; set; }
        public Nullable<int> RelationShipID { get; set; }
    
        public virtual BequeathType BequeathType { get; set; }
        public virtual RelationShip RelationShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientWill> ClientWills { get; set; }
    }
}
