//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WillDefinition
    {
        public int WillDefinitions { get; set; }
        public Nullable<int> WillID { get; set; }
        public Nullable<int> DefinitionsID { get; set; }
    
        public virtual Definition Definition { get; set; }
        public virtual Will Will { get; set; }
    }
}
